# ===================================
#  List Behavior Config
# ===================================

title: winter.notify::lang.notifications.menu_label
list: $/winter/notify/models/notificationrule/columns.yaml
modelClass: Winter\Notify\Models\NotificationRule
recordUrl: winter/notify/notifications/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 30
showSetup: true
showCheckboxes: true
defaultSort:
    column: count
    direction: desc

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt
